stages:
  - build
  - test
  - deploy

variables:
  NODE_VERSION: "20"

cache:
  paths:
    - node_modules/

before_script:
  - node -v
  - npm -v

build:
  stage: build
  image: node:${NODE_VERSION}
  script:
    - echo "Installing dependencies..."
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist
  only:
    - main

test:
  stage: test
  image: node:${NODE_VERSION}
  script:
    - echo "Running tests..."
    - npm test
  dependencies:
    - build
  only:
    - main

deploy:
  stage: deploy
  image: node:${NODE_VERSION}
  script:
    - echo "Deploying application..."
    - npm run deploy
  dependencies:
    - build
  only:
    - main
