stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  image: maven:3.9.6-eclipse-temurin-17
  script:
    - echo "Starting build stage..."
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 hour

test-job:
  stage: test
  image: maven:3.9.6-eclipse-temurin-17
  script:
    - echo "Running tests..."
    - mvn test
  dependencies:
    - build-job

deploy-job:
  stage: deploy
  image: alpine:latest
  script:
    - echo "Deploying application..."
    # Example deployment command:
    # - scp target/*.jar user@your-server:/path/to/deploy/
    # OR for Heroku:
    # - curl https://cli-assets.heroku.com/install.sh | sh
    # - heroku deploy:jar target/*.jar --app your-heroku-app
    - echo "Deployment complete!"
  only:
    - main
